project_id = "xleotnpiheyylvchfyhg"

[functions.gerar-pix]
verify_jwt = false

[functions.criar-usuario]
verify_jwt = false

[functions.login-telefone]
verify_jwt = false

[functions.auto-loja]
verify_jwt = false

[functions.verificar-pix]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.notificar-pedido]
verify_jwt = false
